name: Build and Release Folia

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * 2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Clone Folia repository
        run: git clone https://github.com/PaperMC/Folia.git

      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Build project
        working-directory: Folia
        env:
          GRADLE_OPTS: "-Xmx1g -Xms512m -Dorg.gradle.parallel=false"
        run: |
          # apply patches to paper/minecraft code
          ./gradlew applyAllPatches --info
          # build the decompiled + paper code into a bundled jar
          ./gradlew createMojmapBundlerJar --info

      - name: List all JARs in build/libs (for debugging)
        run: ls -1 Folia/folia-server/build/libs/*.jar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: folia-artifacts
          path: Folia/folia-server/build/libs/folia-bundler-*mojmap.jar
          if-no-files-found: error
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: folia-artifacts

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Folia build at ${{ steps.date.outputs.date }}
          tag_name: build-${{ github.run_id }}
          files: folia-bundler-*-mojmap.jar
          body: "Automated Folia build created on ${{ steps.date.outputs.date }}"
          draft: false
          prerelease: false
          generate_release_notes: true
